# Static Constants for News Curation Pipeline
# =============================================

# -----------------------------
# Company Aliases for Validation
# -----------------------------
INTERNAL_DEDUPE_COLS = ["er_uri", "er_is_duplicate", "er_original_uri", "dup_group_id"]

COMPANY_ALIASES = {
    "Ollion, Inc.": ["Ollion", "Ollion Inc", "Ollion, Inc."],
    "3M Company": ["3M", "3M Company", "Minnesota Mining and Manufacturing"],
    "Abacus Dx Pty Ltd": ["Abacus Dx", "Abacus Dx Pty Ltd", "Abacus"],
    "Abbott Laboratories": ["Abbott", "Abbott Laboratories"],
    "American Banknote Corporation": ["American Banknote", "American Banknote Corporation", "ABCorp"],
    "Accenture PLC": ["Accenture", "Accenture PLC", "Accenture Plc"],
    "ACI Worldwide, Inc.": ["ACI", "ACI Worldwide", "ACI Worldwide Inc"],
    "Acrelec Group SAS": ["Acrelec", "Acrelec Group", "Acrelec Group SAS"],
    "ADM Systems Pty Ltd": ["ADM Systems", "ADM Systems Pty Ltd", "ADM"],
    "Adobe Inc.": ["Adobe", "Adobe Inc", "Adobe Systems"],
    "Adyen N.V.": ["Adyen", "Adyen N.V."],
    "AKQA Inc.": ["AKQA", "AKQA Inc"],
    "Altametrics, LLC": ["Altametrics", "Altametrics LLC"],
    "Ansell Limited": ["Ansell", "Ansell Limited"],
    "Apple Inc.": ["Apple", "Apple Inc"],
    "Aptitude Software Group plc": ["Aptitude", "Aptitude Software", "Aptitude Software Group plc"],
    "Webcentral Limited": ["Webcentral", "Webcentral Limited"],
    "ASSA ABLOY AB": ["ASSA ABLOY", "ASSA ABLOY AB"],
    "AT&T Inc.": ["AT&T", "AT&T Inc"],
    "Atos SE": ["Atos", "Atos SE"],
    "Australia and New Zealand Banking Group Limited": [
        "ANZ",
        "Australia and New Zealand Banking Group",
        "ANZ Bank"
    ],
    "Australian Postal Corporation": ["Australia Post", "Australian Postal Corporation", "StarTrack"],
    "Automatic Data Processing, Inc.": ["ADP", "Automatic Data Processing", "Automatic Data Processing Inc"],
    "Avanade Inc.": ["Avanade", "Avanade Inc"],
    "Avaya Inc.": ["Avaya", "Avaya Inc"],
    "Amazon Web Services, Inc.": ["AWS", "Amazon Web Services", "Amazon Web Services Inc"],
    "Bailiwick Services, LLC": ["Bailiwick Services", "Bailiwick Services LLC"],
    "Beckman Coulter, Inc.": ["Beckman Coulter", "Beckman Coulter Inc"],
    "Becton, Dickinson and Company": ["BD", "Becton Dickinson", "Becton, Dickinson and Company"],
    "BerkOne, Inc.": ["BerkOne", "BerkOne Inc"],
    "Bio-Rad Laboratories, Inc.": ["Bio-Rad", "Bio-Rad Laboratories", "Bio-Rad Laboratories Inc"],
    "Bio-Strategy Pty Ltd": ["Bio-Strategy", "Bio Strategy", "Bio-Strategy Pty Ltd"],
    "BNY Trust Company of Australia Limited": [
        "BNY Trust",
        "BNY Trust Australia",
        "BNY Trust Company of Australia Limited"
    ],
    "British Telecommunications plc": ["BT", "British Telecommunications", "British Telecommunications plc"],
    "Canon Finance Australia Limited": ["Canon Finance", "Canon Finance Australia Limited"],
    "Capgemini SE": ["Capgemini", "Capgemini SE"],
    "CGI Inc.": ["CGI", "CGI Inc"],
    "Cigniti Technologies Limited": ["Cigniti", "Cigniti Technologies", "Cigniti Technologies Limited"],
    "Cisco Systems, Inc.": ["Cisco", "Cisco Systems", "Cisco Systems Inc"],
    "Clear Junction Limited": ["Clear Junction", "Clear Junction Limited"],
    "Coates Hire Operations Pty Limited": ["Coates Hire", "Coates Hire Operations Pty Limited"],
    "Cognizant Technology Solutions Corporation": [
        "Cognizant",
        "Cognizant Technology Solutions",
        "CTS"
    ],
    "Comarch SA": ["Comarch", "Comarch SA"],
    "Computershare Limited": ["Computershare", "Computershare Limited"],
    "Computype, Inc.": ["Computype", "Computype Inc"],
    "Cuscal Limited": ["Cuscal", "Cuscal Limited"],
    "Cushman & Wakefield plc": ["Cushman & Wakefield", "C&W", "Cushman & Wakefield plc"],
    "Databricks, Inc.": ["Databricks", "Databricks Inc"],
    "Datavail Corporation": ["Datavail", "Datavail Corporation"],
    "DAVACO, LP": ["DAVACO", "DAVACO LP"],
    "Dell Technologies Inc.": ["Dell", "Dell Technologies", "Dell Technologies Inc"],
    "Deloitte Touche Tohmatsu Limited": [
        "Deloitte",
        "Deloitte Touche Tohmatsu",
        "DTT"
    ],
    "Dentons Australia Limited": ["Dentons", "Dentons Australia", "Dentons Australia Limited"],
    "DHL Supply Chain (Australia) Pty Limited": [
        "DHL",
        "DHL Supply Chain",
        "DHL Supply Chain Australia"
    ],
    "Diebold Nixdorf, Incorporated": ["Diebold Nixdorf", "Diebold", "Nixdorf"],
    "DoorDash, Inc.": ["DoorDash", "DoorDash Inc"],
    "Duck Creek Technologies, LLC": ["Duck Creek", "Duck Creek Technologies", "Duck Creek"],
    "DXC Technology Company": ["DXC", "DXC Technology", "DXC Technology Company"],
    "Earnix Ltd.": ["Earnix", "Earnix Ltd"],
    "EPAM Systems, Inc.": ["EPAM", "EPAM Systems", "EPAM Systems Inc"],
    "Equifax Inc.": ["Equifax", "Equifax Inc"],
    "Equinix, Inc.": ["Equinix", "Equinix Inc"],
    "Equinix Australia Pty Ltd": ["Equinix Australia", "Equinix AU", "Equinix"],
    "Ernst & Young Global Limited": ["EY", "Ernst & Young", "Ernst & Young Global Limited"],
    "Experian plc": ["Experian", "Experian plc"],
    "Meta Platforms, Inc.": ["Meta", "Meta Platforms", "Facebook"],
    "Federal Express Corporation": ["FedEx", "Federal Express", "Federal Express Corporation"],
    "Fiserv, Inc.": ["Fiserv", "Fiserv Inc"],
    "Fidelity National Information Services, Inc.": [
        "FIS",
        "Fidelity National Information Services",
        "Fidelity National Information Services Inc"
    ],
    "Fivetran Inc.": ["Fivetran", "Fivetran Inc"],
    "Fujitsu Limited": ["Fujitsu", "Fujitsu Limited"],
    "Genesys Cloud Services, Inc.": ["Genesys", "Genesys Cloud", "Genesys Cloud Services"],
    "Genpact Limited": ["Genpact", "Genpact Limited"],
    "Globant S.A.": ["Globant", "Globant S.A."],
    "Google LLC": ["Google", "Google LLC", "Alphabet"],
    "International Business Machines Corporation": [
        "IBM",
        "International Business Machines",
        "IBM Corporation"
    ],
    "Illumina, Inc.": ["Illumina", "Illumina Inc"],
    "Informatica Inc.": ["Informatica", "Informatica Inc"],
    "Infosys Limited": ["Infosys", "Infosys Limited"],
    "Iron Mountain Incorporated": ["Iron Mountain", "Iron Mountain Incorporated"],
    "JetBrains s.r.o.": ["JetBrains", "JetBrains s.r.o."],
    "Jones Lang LaSalle Incorporated": ["JLL", "Jones Lang LaSalle", "Jones Lang LaSalle Incorporated"],
    "Kyndryl Holdings, Inc.": ["Kyndryl", "Kyndryl Holdings", "Kyndryl Holdings Inc"],
    "LTIMindtree Limited (formerly LTI)": [
        "LTIMindtree",
        "LTI",
        "Mindtree"
    ],
    "LTIMindtree Limited": ["LTIMindtree", "LTIMindtree Limited"],
    "Microsoft Corporation": ["Microsoft", "Microsoft Corporation"],
    "Mphasis Limited": ["Mphasis", "Mphasis Limited"],
    "NCR Voyix Corporation": ["NCR Voyix", "NCR", "NCR Corporation"],
    "NCR Atleos Corporation": ["NCR Atleos", "Atleos", "NCR"],
    "New Relic, Inc.": ["New Relic", "New Relic Inc"],
    "Okta, Inc.": ["Okta", "Okta Inc"],
    "Oracle Corporation": ["Oracle", "Oracle Corporation"],
    "Palo Alto Networks, Inc.": ["Palo Alto Networks", "PAN", "Palo Alto Networks Inc"],
    "Pegasystems Inc.": ["Pegasystems", "Pega", "Pegasystems Inc"],
    "Persistent Systems Limited": ["Persistent", "Persistent Systems", "Persistent Systems Limited"],
    "Salesforce, Inc.": ["Salesforce", "Salesforce Inc"],
    "SAP SE": ["SAP", "SAP SE"],
    "Tata Consultancy Services Limited": ["TCS", "Tata Consultancy Services", "Tata Consultancy Services Limited"],
    "Tech Mahindra Limited": ["Tech Mahindra", "Tech Mahindra Limited"],
    "Telstra Group Limited": ["Telstra", "Telstra Group Limited"],
    "Temenos AG": ["Temenos", "Temenos AG"],
    "Thermo Fisher Scientific Inc.": [
        "Thermo Fisher",
        "Thermo Fisher Scientific",
        "Thermo Fisher Scientific Inc"
    ],
    "Uber Technologies, Inc.": ["Uber", "Uber Technologies", "Uber Technologies Inc"],
    "UBS Group AG": ["UBS", "UBS Group", "UBS Group AG"],
    "Unisys Corporation": ["Unisys", "Unisys Corporation"],
    "UST Global Inc.": ["UST", "UST Global", "UST Global Inc"],
    "Verifone, Inc.": ["Verifone", "Verifone Inc"],
    "Verizon Communications Inc.": ["Verizon", "Verizon Communications", "Verizon Communications Inc"],
    "Virtusa Corporation": ["Virtusa", "Virtusa Corporation"],
    "VMware, Inc.": ["VMware", "VMware Inc"],
    "Westpac Banking Corporation": ["Westpac", "Westpac Banking Corporation"],
    "Wipro Limited": ["Wipro", "Wipro Limited"],
    "WNS (Holdings) Limited": ["WNS", "WNS Holdings", "WNS (Holdings) Limited"],
    "Zebra Technologies Corporation": ["Zebra", "Zebra Technologies", "Zebra Technologies Corporation"],
    "Zuora, Inc.": ["Zuora", "Zuora Inc"],
    "Digi-Trax Corporation": ["Digi-Trax", "Digi-Trax Corporation"],
    "Epsilon Data Management, LLC": ["Epsilon", "Epsilon Data Management", "Epsilon Data Management LLC"],
    "EXL Service Australia Pty Ltd": ["EXL", "EXL Service", "EXL Service Australia"],
    "Famar Health Care Services": ["Famar", "Famar Health Care Services"],
    "Feedzai Inc.": ["Feedzai", "Feedzai Inc"],
    "First Data Corporation": ["First Data", "First Data Corporation", "Fiserv First Data"],
    "Fresenius Kabi AG": ["Fresenius Kabi", "Fresenius Kabi AG"],
    "Fujifilm Business Innovation Corp.": [
        "Fujifilm Business Innovation",
        "Fuji Xerox",
        "Fujifilm Business Innovation Corp"
    ],
    "Gadens Lawyers Melbourne Pty Ltd": ["Gadens", "Gadens Lawyers", "Gadens Lawyers Melbourne"],
    "Gathi Analytics, LLC": ["Gathi Analytics", "Gathi Analytics LLC"],
    "GEP Worldwide": ["GEP", "GEP Worldwide"],
    "Grifols, S.A.": ["Grifols", "Grifols S.A."],
    "Haemonetics Corporation": ["Haemonetics", "Haemonetics Corporation"],
    "HCL Technologies Limited": ["HCL", "HCL Technologies", "HCL Technologies Limited"],
    "Hitachi, Ltd.": ["Hitachi", "Hitachi Ltd"],
    "Honeycomb Agency Pty Ltd": ["Honeycomb Agency", "Honeycomb Agency Pty Ltd"],
    "uCloudlink Group Inc.": ["uCloudlink", "uCloudlink Group", "uCloudlink Group Inc"],
    "illion Australia Pty Ltd": ["illion", "illion Australia", "illion Australia Pty Ltd"],
    "Insight Enterprises, Inc.": ["Insight", "Insight Enterprises", "Insight Enterprises Inc"],
    "Interpath Services Pty Ltd": ["Interpath", "Interpath Services", "Interpath Services Pty Ltd"],
    "Information Services Group, Inc.": ["ISG", "Information Services Group", "Information Services Group Inc"],
    "ITC Infotech India Limited": ["ITC Infotech", "ITC Infotech India", "ITC Infotech India Limited"],
    "Korn Ferry": ["Korn Ferry", "Korn Ferry International"],
    "Lash Creative Pty Ltd": ["Lash Creative", "Lash Creative Pty Ltd"],
    "Lens10 Pty Ltd": ["Lens10", "Lens10 Pty Ltd"],
    "Link Administration Holdings Limited": ["Link Group", "Link Administration", "Link Administration Holdings Limited"],
    "LivePerson, Inc.": ["LivePerson", "LivePerson Inc"],
    "Lumen Technologies, Inc.": ["Lumen", "Lumen Technologies", "CenturyLink"],
    "Macopharma SA": ["Macopharma", "Macopharma SA"],
    "MAPS Group": ["MAPS Group", "MAPS"],
    "Marketing Technology Partners UK Limited (MAPS Group)": [
        "Marketing Technology Partners",
        "MAPS Group",
        "MTP"
    ],
    "Marketo, Inc. (Adobe)": ["Marketo", "Adobe Marketo", "Marketo Inc"],
    "Millennium Science Pty Ltd": ["Millennium Science", "Millennium Science Pty Ltd"],
    "Miracle Software Systems, Inc.": ["Miracle Software Systems", "Miracle Software", "Miracle Software Systems Inc"],
    "Mu Sigma Business Solutions Pty Ltd": ["Mu Sigma", "Mu Sigma Business Solutions", "Mu Sigma Australia"],
    "Nextgen.Net Pty Ltd": ["Nextgen", "Nextgen.Net", "Nextgen.Net Pty Ltd"],
    "Nippon Telegraph and Telephone Corporation": ["NTT", "Nippon Telegraph and Telephone", "NTT Group"],
    "OBS (Empired Limited)": ["OBS", "Empired", "Empired Limited"],
    "Opteon Property Group Pty Ltd": ["Opteon", "Opteon Property Group", "Opteon Property Group Pty Ltd"],
    "Singtel Optus Pty Limited": ["Optus", "Singtel Optus", "Optus Australia"],
    "Orange S.A.": ["Orange", "Orange S.A."],
    "Panasonic Holdings Corporation": ["Panasonic", "Panasonic Holdings", "Panasonic Corporation"],
    "PAR Technology Corporation": ["PAR Technology", "PAR", "PAR Technology Corporation"],
    "Paragon Care Limited": ["Paragon Care", "Paragon Care Limited"],
    "Perfecto Mobile, Inc.": ["Perfecto", "Perfecto Mobile", "Perfecto Mobile Inc"],
    "Photon Interactive Services, Inc.": ["Photon", "Photon Interactive", "Photon Interactive Services Inc"],
    "Plexure Group Limited": ["Plexure", "Plexure Group", "Plexure Group Limited"],
    "Preston Rowe Paterson Australasia Pty Ltd": [
        "Preston Rowe Paterson",
        "PRP",
        "Preston Rowe Paterson Australasia"
    ],
    "QIAGEN N.V.": ["QIAGEN", "QIAGEN N.V."],
    "QSRSoft, Inc.": ["QSRSoft", "QSRSoft Inc"],
    "Quadient SA": ["Quadient", "Quadient SA", "Neopost"],
    "Rackspace Technology, Inc.": ["Rackspace", "Rackspace Technology", "Rackspace Technology Inc"],
    "Radware Ltd.": ["Radware", "Radware Ltd"],
    "Randstad N.V.": ["Randstad", "Randstad N.V."],
    "Reckitt Benckiser Group plc": ["Reckitt", "Reckitt Benckiser", "RB"],
    "ReSource Pro, LLC": ["ReSource Pro", "ReSource Pro LLC"],
    "CoreLogic RP Data (RP Data Pty Ltd)": ["CoreLogic", "RP Data", "CoreLogic RP Data"],
    "Saba Software, Inc.": ["Saba", "Saba Software", "Saba Software Inc"],
    "Publicis Sapient": ["Publicis Sapient", "Sapient", "Sapient Publicis"],
    "Serraview Australia Pty Ltd": ["Serraview", "Serraview Australia", "Serraview Australia Pty Ltd"],
    "Servian Pty Ltd": ["Servian", "Servian Pty Ltd"],
    "SessionM, Inc.": ["SessionM", "SessionM Inc"],
    "Shrishti Software Applications Pvt Ltd": ["Shrishti Software", "Shrishti Software Applications"],
    "Sift Science, Inc.": ["Sift", "Sift Science", "Sift Science Inc"],
    "Sirius Computer Solutions, Inc.": ["Sirius Computer Solutions", "Sirius", "Sirius Computer Solutions Inc"],
    "Sitecore Holding II A/S": ["Sitecore", "Sitecore Holding", "Sitecore A/S"],
    "Sophartex SA": ["Sophartex", "Sophartex SA"],
    "Span.io": ["Span", "Span.io"],
    "SS&C Technologies Holdings, Inc.": ["SS&C", "SS&C Technologies", "SS&C Technologies Holdings Inc"],
    "StarTrack (Australian Postal Corporation)": ["StarTrack", "Star Track", "Australia Post StarTrack"],
    "State Street Corporation": ["State Street", "State Street Corporation"],
    "STEMCELL Technologies Inc.": ["STEMCELL", "STEMCELL Technologies", "STEMCELL Technologies Inc"],
    "Society for Worldwide Interbank Financial Telecommunication": ["SWIFT", "Society for Worldwide Interbank Financial Telecommunication"],
    "Tecan Group Ltd.": ["Tecan", "Tecan Group", "Tecan Group Ltd"],
    "Teleperformance SE": ["Teleperformance", "Teleperformance SE"],
    "Terumo Corporation": ["Terumo", "Terumo Corporation"],
    "Terumo BCT, Inc.": ["Terumo BCT", "Terumo BCT Inc"],
    "Thales DIS (Digital Identity and Security)": ["Thales DIS", "Thales Digital Identity", "Thales"],
    "The Little Big Dairy Company Pty Ltd": ["The Little Big Dairy Company", "Little Big Dairy"],
    "Thrive Networks, Inc.": ["Thrive Networks", "Thrive Networks Inc"],
    "Toll Holdings Limited": ["Toll", "Toll Holdings", "Toll Group"],
    "Toshiba Corporation": ["Toshiba", "Toshiba Corporation"],
    "T-Systems International GmbH": ["T-Systems", "T-Systems International", "T Systems"],
    "Umain AB": ["Umain", "Umain AB"],
    "Valocity Limited": ["Valocity", "Valocity Limited"],
    "Verint Systems (Australia) Pty Ltd": ["Verint", "Verint Systems", "Verint Australia"],
    "Waybright Partners": ["Waybright", "Waybright Partners"],
    "Intrado Corporation": ["Intrado", "Intrado Corporation"],
    "Xoriant Corporation": ["Xoriant", "Xoriant Corporation"]
}

# -----------------------------
# QC Tags for News Tagging
# -----------------------------
QC_TAGS = [
    "Inappropriate Content: The article contains sexually explicit or pornographic or gambling material that is not suitable for general audiences.",
    "Stock Market Related: The article where the primary theme centers on stock sales, purchases, market predictions, or financial trading. Mentions of stocks or shares are acceptable if they are incidental and not the main subject of the article.",
    "Unstructured News: The article is poorly formatted, with missing paragraphs, broken hyperlinks, or irrelevant text fragments that disrupt readability and comprehension.",
    "Headline Correction: The headline includes extra or malformed text due to formatting issues, such as appended metadata, navigation links, or unrelated phrases.",
    "Advertisement Reference Only : The article is incorrectly tagged due to the presence of advertisements (e.g., Apple AirPods) that are unrelated to the actual news content.",
    "Incorrect Company Tagging : The article is tagged under a Company, but the content does not mention or relate to that Company in any meaningful way.",
    "Non English text: The article is not in the english language.",
    
    """Blogpost: Tag as 'blogpost' if source is a personal blog (Medium, WordPress, Substack personal, etc), 
    tutorial/educational site (Dev.to, Hashnode, etc), review site (G2, Capterra, TrustRadius, etc), 
    forum (Reddit, Quora, Stack Overflow, etc), social media post (Twitter/X, Facebook unless official account, etc), 
    affiliate site, content farm. 
    Tag as 'blogpost' if URL contains patterns like medium.com/@, wordpress.com, blogspot.com, 
    substack.com/@, dev.to/, or /blog/ not on a company domain, or has excessive hyphens/numbers. 
    Also tag as 'blogpost' if author is listed as Guest Author, Contributor, Community Member, freelance, 
    independent, or consultant (unless from major outlet), has no author attribution, affiliate disclosures, 
    or promotes competing products. 
    Do NOT tag as blogpost if author is a company executive/spokesperson on 
    official site, or a staff writer/journalist for a recognized publication, or if it's a press release 
    (PR Newswire, Business Wire, etc.).
    Do NOT tag as blogpost if it comes from official company sources (press releases, newsroom, 
    investor relations, official social media, or company blog labeled as News/Press Releases) or major 
    news outlets (Reuters, AP, Bloomberg, AFP, WSJ, FT, Forbes, Fortune, TechCrunch, The Verge, 
    Ars Technica, CNET, ZDNet, Computerworld, InformationWeek, CIO.com, or regional business journals). 
    Valid content types include breaking news, financial results, M&A, product launches, partnerships, 
    executive appointments, major deals, expansions, or regulatory actions. 
    
""",
    
    """Market Research: Tag as 'market_research' if it discusses market analysis, research studies, 
    industry trends, sector performance, forecasts, growth projections, competitive landscape, 
    consumer insights, demand/supply analysis, pricing trends, or statistical findings about a market or product category.
    Also include academic or industry research published by recognized institutions or consulting firms 
    if the focus is on market data or trends. 
    Do NOT tag as 'market_research' if the content is a company press release, corporate announcement, 
    product launch, financial earnings report, executive appointment, partnership news, regulatory filing, 
    event coverage, or opinion piece. Exclude generic news articles, blogs, or announcements that only 
    mention the market tangentially without presenting structured research, data, or forecast analysis.""",
    
    """Awards: Tag as 'awards' if the article announces that a company, product, service, internal employee recognition,
    promotional giveaways,  or marketing campaigns, or executive 
    has received an award, recognition, ranking, certification, or honor from an external organization, 
    industry body, media outlet, or event. Examples include 'Best Workplace Award', 'Top 100 Companies', 
    'Innovation Excellence Award', or 'CEO of the Year'. 
    Do NOT tag as 'Awards' if the content just mentioned only in passing 
    without being the main subject of the article.""",
    
    """Company Study: Studies Conducted by Companies Tag as 'company_study' if the article reports on surveys, 
    research studies, whitepapers, or data-driven analyses conducted or commissioned by a company. 
    This includes consumer behavior surveys, employee engagement studies, product usage reports, 
    industry insights, or proprietary research findings published by the company itself. 
    Do NOT tag as 'company_study' if the article only references third-party research (e.g., 
    academic institutions, consulting firms, government agencies) without the company being the 
    primary source or conductor of the study. Exclude generic mentions of 'studies show' unless 
    the company is explicitly identified as the author or sponsor of the research."""

]

# -----------------------------
# Blog Platform Detection
# -----------------------------
BLOG_PLATFORMS = [
    'medium.com',
    'wordpress.com',
    'blogspot.com',
    'blogger.com',
    'substack.com',
    'dev.to',
    'hashnode.dev',
    'tumblr.com',
    'digit.in',
    "geeky-gadgets.com ",
    'x.com',
    'reddit.com',
    'tomsguide.com',
    'citywire.com',
    
    '7news.com.au',
    'aboutchromebooks.com',
    'ad-hoc-news.de',
    'africaintelligence.com',
    'androidauthority.com',
    'apple.gadgethacks.com',
    'au.headtopics.com',
    'bdtonline.com',
    'benzinga.com',
    'beritaja.com',
    'berkshireeagle.com',
    'besacenter.org',
    'bloomberg.com',
    'business-standard.com',
    'coingeek.com',
    'community.broadcom.com',
    'cordcuttersnews.com',
    'cryptoslate.com',
    'dailydot.com',
    'dailyexcelsior.com',
    'dailypolitical.com',
    'databricks.com',
    'devonlive.com',
    'dig-in.com',
    'droid-life.com',
    'eagletribune.com',
    'economictimes.indiatimes.com',
    'essfeed.com',
    'fibre2fashion.com',
    'fierce-network.com',
    'financialexpress.com',
    'finimize.com',
    'fonearena.com',
    'forums.macrumors.com',
    'gadgetreview.com',
    'geeky-gadgets.com',
    'globenewswire.com',
    'gobankingrates.com',
    'guidingtech.com',
    'hellofuture.orange.com',
    'idropnews.com',
    'itnews.com.au',
    'itnewsonline.com',
    'jowhar.com',
    'law360.com',
    'livemint.com',
    'lse.co.uk',
    'macdailynews.com',
    'marketbeat.com',
    'markets.businessinsider.com',
    'marketscreener.com',
    'mlex.com',
    'moneycontrol.com',
    'morningbrew.com',
    'newcastleherald.com.au',
    'news.bloomberglaw.com',
    'newsdirectory3.com',
    'newspatrolling.com',
    'newstalk1280.com',
    'nextgov.com',
    'openpr.com',
    'phonearena.com',
    'pocket-lint.com',
    'pressherald.com',
    'proactiveinvestors.com',
    'prsync.com',
    'reformer.com',
    'romania-insider.com',
    'securityboulevard.com',
    'seekingalpha.com',
    'siliconangle.com',
    'straitstimes.com',
    'tech.yahoo.com',
    'techradar.com',
    'telecomtalk.info',
    'timesofindia.indiatimes.com',
    'tmonews.com',
    'tomsguide.com',
    'travelandtourworld.com',
    'uk.pcmag.com',
    'vccircle.com',
    'webpronews.com',
    'westernweekender.com.au',
    'whatech.com',
    'wobm.com',
    'xda-developers.com',
    'zdnet.com'

    # 'https://www.geeky-gadgets.com/m6-macbook-pro-2/',
    # 'https://www.phonearena.com/news/iphone-18-pro-series-might-have-breakout-feature_id177516',
    # 'https://economictimes.indiatimes.com/news/international/australia/quote-of-the-day-by-apple-ceo-tim-cook-let-your-joy-be-in-your-journey-not-in-some-/articleshow/126948394.cms',
    # 'https://www.phonearena.com/news/att-and-verizon-customers-hoping-for-justice-by-supreme-court_id177507',
    # 'https://www.databricks.com/blog/alchemist-brickbuilder-databricks-marketplace-app',
    # 'https://www.zdnet.com/article/ai-agent-deployment-in-workplace-outpaces-safety-protocols-deloitte-says/',
    # 'https://coingeek.com/?p=614858',
    # 'https://www.techradar.com/pro/rackspace-email-hosting-price-hike-will-be-devastating-customers-say',
    # 'https://wobm.com/ixp/385/p/verizon-service-disruption-nj/',
    # 'https://www.vccircle.com/wiproceo-sees-growing-demand-for-india-s-it-services-from-ai',
    # 'https://seekingalpha.com/article/4861687-accenture-stock-bullish-technical-setup-i-starting-position-technical-analysis',
    # 'https://cordcuttersnews.com/xfinity-att-verizon-top-list-of-companies-that-frustrated-customers-the-most-in-2025/',
    # 'https://www.droid-life.com/2026/01/21/device-unlock-policy-t-mobile-verizon-att/',
    # 'https://newstalk1280.com/ixp/721/p/doordash-popular-food-super-bowl-sunday/',
    # 'https://finimize.com/content/bofa-trimmed-experian-forecasts-but-kept-its-buy-call',
    # 'https://www.tomsguide.com/ai/google-gemini-is-basically-running-my-side-hustle-for-me-heres-how',
    # 'https://www.nextgov.com/sponsors/2025/12/empowering-national-design-studios-vision-salesforce-personalization/410366/',
    # 'https://timesofindia.indiatimes.com/business/india-business/how-fm-can-simplify-tcs-to-ease-cash-flow-pressure/articleshow/127052518.cms',
    # 'https://cordcuttersnews.com/xfinity-att-verizon-top-list-of-companies-that-frustrated-customers-the-most-in-2025/',
    # 'https://www.droid-life.com/2026/01/21/device-unlock-policy-t-mobile-verizon-att/',
    # 'https://www.idropnews.com/news/verizon-prepaid-iphone-365-day-unlock-policy-change/258596/',
    # 'https://community.broadcom.com/vmware-cloud-foundation/discussion/nested-esxi-7-virtual-machine-will-not-power-on-after-upgrading-to-workstation-pro-25h2',
    # 'https://community.broadcom.com/vmware-cloud-foundation/discussion/vm-rightsizing-recommendations',
    # 'https://www.webpronews.com/adobe-taps-airbnb-tech-veteran-lucius-diphillips-as-cio-to-fuel-ai-push/',
    # 'https://www.webpronews.com/wine-patches-unlock-adobe-photoshop-native-run-on-linux/',
    # 'https://telecomtalk.info/can-apple-pay-eat-up-google-pay/1003796/',
    # 'https://www.webpronews.com/meta-battles-to-exclude-key-evidence-in-new-mexico-child-harm-lawsuit/',
    # 'https://www.proactiveinvestors.com/companies/news/1086128/ibm-software-growth-seen-reaccelerating-ahead-of-earnings-jefferies-1086128.html',
    # 'https://www.guidingtech.com/how-to-fix-microsoft-authenticator-shows-wrong-location/',
    # 'https://hellofuture.orange.com/en/orange-opentech-2025-ai-at-the-service-of-innovation/',
    # 'https://www.newsdirectory3.com/trumps-verizon-making-it-harder-to-switch-mobile-carriers/',
    # 'https://markets.businessinsider.com/news/stocks/analysts-conflicted-on-these-healthcare-names-intuitive-surgical-isrg-and-abbott-laboratories-abt-1035743232',
    # 'https://www.marketscreener.com/news/abbott-laboratories-medtech-business-sustains-momentum-amid-nutrition-weakness-ubs-says-ce7e5bdadc8cf325',
    # 'https://www.aboutchromebooks.com/adobe-qr-code-generator/',
    # 'https://www.xda-developers.com/getting-adobe-photoshop-on-linux-just-took-a-big-step-forward/',
    # 'https://www.ad-hoc-news.de/boerse/ueberblick/adobe-premiere-pro-review-is-this-the-video-editor-that-finally-makes-you/68519228',
    # 'https://macdailynews.com/2026/01/26/apple-preps-new-macbook-pro-macbook-air-and-mac-studio-models/',
    # 'https://au.headtopics.com/news/7you-reviews-the-iphone-air-the-camera-backlash-misses-78911673',
    # 'https://apple.gadgethacks.com/how-to/apple-watch-gets-ai-workout-buddy-in-ios-26-watchos-26/',
    # 'https://www.pocket-lint.com/can-you-use-apple-carplay-without-the-internet/',
    # 'https://forums.macrumors.com/threads/could-you-see-apple-making-a-dedicated-camera.2476684/',
    # 'https://www.phonearena.com/news/new-report-reveals-why-giving-your-apple-watch-data-to-ai-doctors-might-be-a-bad-idea_id177699',
    # 'https://www.devonlive.com/whats-on/shopping/bt-ee-broadband-bills-cost-10768509',
    # 'https://cryptoslate.com/companies/deloitte/',
    # 'https://www.zdnet.com/article/future-of-gmail-ai-interview-blake-barnes/',
    # 'https://securityboulevard.com/2026/01/imperva-customers-protected-against-cve-2026-21962-in-oracle-http-and-weblogic/',
    # 'https://www.financialexpress.com/life/technology-ai-quote-of-the-day-all-ai-models-basically-the-same-claims-oracle-co-founder-larry-ellison-heres-why-4119736/',
    # 'https://siliconangle.com/2026/01/25/salesforce-tries-keep-lid-agentic-sprawl-mulesoft-agent-fabric/',
    # 'https://www.androidauthority.com/time-to-leave-verizon-poll-result-3635056/',
    # 'https://dailydot.com/increase-verizon-outage-credit/',
    # 'https://community.broadcom.com/vmware-cloud-foundation/discussion/cannot-use-cycle-multiple-monitors',
    # 'https://community.broadcom.com/vmware-cloud-foundation/discussion/ai-automation-of-vsphere-and-nsx',
    # 'https://7news.com.au/7you/tech/could-this-rumoured-apple-product-be-the-future-of-how-we-interact-with-ai-c-21451672',
    # 'https://www.westernweekender.com.au/2026/01/the-saga-of-brians-missing-ring-australia-post-and-desperate-plea/',
    # 'https://siliconangle.com/2026/01/27/databricks-reports-finds-surge-ai-agent-adoption-despite-governance-bottlenecks/',
    # 'https://www.fonearena.com/blog/474250/google-photos-conversational-ai-editing-android-india.html',
    # 'https://www.androidauthority.com/google-aluminium-os-first-look-bug-report-3635801/',
    # 'https://www.newsdirectory3.com/yahoo-scout-vs-perplexity-google-ai-the-new-ai-answer-engine/',
    # 'https://beritaja.com/google-photos-brings-its-prompt-based-editing-feature-to-india-australia-and-japan-beritaja-402486.html',
    # 'https://www.moneycontrol.com/technology/google-announces-theft-protection-feature-for-android-devices-here-s-how-it-works-article-13794319.html',
    # 'https://www.xda-developers.com/here-are-all-the-new-features-microsoft-added-to-excel-in-january-2026/',
    # 'https://www.benzinga.com/markets/tech/26/01/50180124/chamath-palihapitiyas-nervous-gulp-a-sign-of-things-to-come-oracles-credit-default-swaps-surge-past-covid-19-levels',
    # 'https://www.fierce-network.com/wireless/verizon-didnt-trigger-price-war-analysts',
    # 'https://www.phonearena.com/news/verizon-customer-perception-change-after-outage_id177733',
    # 'https://www.gadgetreview.com/verizon-traps-your-phone-for-365-days-and-the-fcc-just-said-thats-fine',
    # 'https://www.droid-life.com/2026/01/27/device-unlock-policy-t-mobile-verizon-att/',
    # 'https://www.techradar.com/phones/verizon/verizon-issues-rare-refund-to-boston-users-who-are-locked-out-of-key-tv-channels-to-show-that-we-have-their-back',
    # 'https://www.itnews.com.au/news/bureau-of-meteorologys-vmware-bill-more-than-doubles-623198',
    # 'https://jowhar.com/slovakia-and-hungary-to-launch-legal-challenge-against-eus-russian-gas-ban/',
    # 'https://www.travelandtourworld.com/news/article/austria-joins-hungary-spain-portugal-iceland-and-other-european-countries-leading-affordable-luxury-museum-tourism-transit-revolution-and-astro-travel-more-news-from-europe/',
    # 'https://newspatrolling.com/feeding-india-releases-2024-25-annual-report-over-23-crore-meals-served-highlights-fight-against-hunger-beyond-classrooms/',
    # 'https://www.travelandtourworld.com/news/article/uk-joins-ireland-france-germany-and-canada-in-issuing-new-travel-advisory-for-us-amid-growing-concerns-everything-you-need-to-know/',
    # 'https://besacenter.org/israels-victory-while-costly-legitimized-the-deal-of-the-century/',
    # 'https://www.financialexpress.com/business/news/whos-winning-the-global-it-race-in-2026-accenture-no-1-indias-big-three-rule-the-global-top-5/4114339/',
    # 'http://prsync.com/market-research-update/how-big-is-the-north-america-accenture-connected-truck-market-size-share-and-forecast-analysis-for--5092353/',
    # 'https://www.openpr.com/news/4357227/music-streaming-market-size-share-growth-status-emerging',
    # 'https://www.openpr.com/news/4357234/thunderbolt-devices-market-size-2026-emerging-demands-share',
    # 'https://www.openpr.com/news/4357252/ocean-power-market-set-for-dynamic-development-with-key-players',
    # 'https://www.openpr.com/news/4357186/united-states-advanced-analytics-market-to-hit-us-108-15',
    # 'https://www.gobankingrates.com/saving-money/food/grubhub-doordash-uber-eats-cheapest-state/',
    # 'https://www.romania-insider.com/romania-mergers-market-ey-2025',
    # 'https://www.moneycontrol.com/news/business/markets/union-budget-2026-agriculture-segment-eyes-digital-infra-rural-credit-reform-13783129.html',
    # 'https://www.openpr.com/news/4357299/neodymium-iron-boron-market-is-expected-to-reach-us-22-2-billion',
    # 'https://www.openpr.com/news/4357206/entity-management-software-market-set-for-rapid-growth-demand',
    # 'https://www.dailyexcelsior.com/tcs-infosys-retain-top-spots-as-indian-it-dominates-global-brand-value-ranking/',
    # 'https://www.openpr.com/news/4357219/marketing-technology-market-size-2026-emerging-demands-share',
    # 'https://www.openpr.com/news/4357206/entity-management-software-market-set-for-rapid-growth-demand',
    # 'https://www.openpr.com/news/4357186/united-states-advanced-analytics-market-to-hit-us-108-15',
    # 'https://www.openpr.com/news/4357219/marketing-technology-market-size-2026-emerging-demands-share',
    # 'https://www.openpr.com/news/4357206/entity-management-software-market-set-for-rapid-growth-demand',
    # 'https://www.openpr.com/news/4357178/it-services-outsourcing-market-size-2026-emerging-demands',
    # 'https://www.dailyexcelsior.com/tcs-infosys-retain-top-spots-as-indian-it-dominates-global-brand-value-ranking/',
    # 'https://itnewsonline.com/PRNewswire/Tech-Mahindra-Advances-to-the-Fourth-Rank-Among-India-Headquartered-IT-Services-Firms-in-Brand-Strength/1106228',
    # 'https://www.openpr.com/news/4357269/north-america-bioinformatics-market-size-share-trends',
    # 'https://www.openpr.com/news/4357055/bovine-plasma-market-size-2026-global-share-industry',
    # 'https://www.openpr.com/news/4356471/automated-cell-imaging-system-market-valuation-expected-to-hit',
    # 'https://www.openpr.com/news/4356518/facts-flexible-ac-transmission-system-market-valuation',
    # 'https://www.openpr.com/news/4359435/internet-of-things-iot-telecom-services-market-valuation',
    # 'https://www.openpr.com/news/4359027/united-states-connectivity-as-a-service-caas-market-to-reach',
    # 'https://www.openpr.com/news/4358472/proteomics-market-dynamics-and-contributions-by-thermo-fisher',
    # 'https://www.openpr.com/news/4358227/apoptosis-assays-market-dynamics-and-contributions-by-merck',
    # 'https://www.openpr.com/news/4359180/application-security-market-to-reach-us-40-62-billion-by-2032',
    # 'https://www.openpr.com/news/4359341/software-testing-and-qa-services-market-size-2026-emerging',
    # 'https://www.openpr.com/news/4359263/business-management-consulting-service-market-covering-prime',
    # 'https://www.openpr.com/news/4359341/software-testing-and-qa-services-market-size-2026-emerging',
    # 'https://www.dig-in.com/news/ey-insurance-m-a-activity-slowed-in-2025',
    # 'https://www.openpr.com/news/4359401/fish-processing-in-2026-full-cost-analysis-investment',
    # 'https://www.openpr.com/news/4358544/ai-driven-seo-campaign-helps-uk-dental-clinic-achieve-top-google',
    # 'https://www.openpr.com/news/4358397/blood-transfusion-diagnostics-covering-prime-factors',
    # 'https://www.openpr.com/news/4358381/blood-group-typing-market-by-top-trending-companies-grifols',
    # 'https://www.openpr.com/news/4358384/blood-plasma-derivatives-covering-prime-factors',
    # 'https://www.openpr.com/news/4358394/blood-screening-covering-prime-factors-and-competitive-outlook',
    # 'https://www.openpr.com/news/4359243/new-horizons-in-hard-ferrite-magnets-market-is-booming-so',
    # 'https://www.openpr.com/news/4359220/mobile-substation-market-to-reach-us-4-10-billion-by-2033-at-9-6',
    # 'https://www.openpr.com/news/4358983/metal-injection-molding-materials-market-set-for-dynamic',
    # 'https://www.openpr.com/news/4359341/software-testing-and-qa-services-market-size-2026-emerging',
    # 'https://www.openpr.com/news/4359245/business-intelligence-and-analytics-market-covering-prime',
    # 'https://www.openpr.com/news/4359263/business-management-consulting-service-market-covering-prime',
    # 'https://www.openpr.com/news/4359180/application-security-market-to-reach-us-40-62-billion-by-2032',
    # 'https://www.openpr.com/news/4359387/relational-database-software-market-valuation-expected-to-hit',
    # 'https://www.openpr.com/news/4359326/software-defined-wide-area-network-market-to-reach-us-18-58',
    # 'https://www.openpr.com/news/4359284/new-horizons-in-high-availability-cluster-software-market-size',
    # 'https://www.openpr.com/news/4359210/trade-finance-market-to-reach-usd-5-2-billion-by-2030-cagr-3-0',
    # 'https://essfeed.com/top-10-oracle-service-networks-feeding-2026-real-world-data-to-smart-contracts/',
    # 'https://www.openpr.com/news/4359113/laser-depaneling-machine-market-in-depth-insights-business',
    # 'https://www.openpr.com/news/4359000/rail-welding-machines-market-2026-2033-industry-insights',
    # 'https://www.openpr.com/news/4358506/future-of-point-of-care-diagnostics-market-analysis-led',
    # 'https://www.openpr.com/news/4358503/key-trends-in-the-occlusion-devices-market-with-insights-from',
    # 'https://www.openpr.com/news/4358493/safety-pen-needles-market-analysis-led-by-bd-novo-nordisk',
    # 'https://www.openpr.com/news/4358462/key-trends-in-the-cell-expansion-market-with-insights-from-ge',
    # 'https://www.openpr.com/news/4358426/bone-growth-stimulator-market-covering-prime-factors',
    # 'https://www.openpr.com/news/4358306/membrane-oxygenator-market-insights-key-players-and-demand',
    # 'https://www.openpr.com/news/4358462/key-trends-in-the-cell-expansion-market-with-insights-from-ge',
    # 'https://www.openpr.com/news/4358472/proteomics-market-dynamics-and-contributions-by-thermo-fisher',
    # 'https://www.openpr.com/news/4358462/key-trends-in-the-cell-expansion-market-with-insights-from-ge',
    # 'https://www.openpr.com/news/4358464/biologics-safety-testing-market-innovations-and-key-players',
    # 'https://www.openpr.com/news/4358451/rapid-microbiology-testing-market-dynamics-and-contributions',
    # 'https://www.openpr.com/news/4358491/future-of-surgical-imaging-market-analysis-led-by-ge',
    # 'https://www.openpr.com/news/4359435/internet-of-things-iot-telecom-services-market-valuation',
    # 'https://www.openpr.com/news/4359027/united-states-connectivity-as-a-service-caas-market-to-reach',
    # 'https://www.openpr.com/news/4359284/new-horizons-in-high-availability-cluster-software-market-size',
    # 'https://www.openpr.com/news/4358278/tracking-as-a-service-market-valuation-expected-to-hit-usd-8-31',
    # 'https://www.openpr.com/news/4361086/smart-food-packaging-market-to-reach-us-38-6b-by-2030-cagr-5-4',
    # 'https://www.openpr.com/news/4360888/5g-conductive-coating-market-booming-worldwide-demand-growth',
    # 'https://www.openpr.com/news/4360828/hazardous-label-market-is-booming-with-strong-growth-prospects',
    # 'https://www.openpr.com/news/4361090/ventricular-tachycardia-ablation-market-market',
    # 'https://www.openpr.com/news/4360936/cardiac-surgical-devices-market-covering-prime-factors',
    # 'https://www.openpr.com/news/4361111/e-merchandising-software-market-is-going-to-boom-adobe',
    # 'https://www.business-standard.com/technology/tech-news/tech-wrap-jan-22-samsung-sound-tower-fujifilm-instax-mini-adobe-ai-126012201034_1.html',
    # 'https://www.openpr.com/news/4361046/refurbished-electronics-market-size-share-2026-analysis',
    # 'https://www.lse.co.uk/news/friday-newspaper-round-up-jpmorgan-chase-apple-nigel-farage-rv7u0fk7lmdio1p.html',
    # 'http://prsync.com/marektsandmarkets/apple-inc-us-and-samsung-south-korea-are-leading-players-in-the-wearable-technology-market-5095731/',
    # 'https://www.morningbrew.com/stories/2026/01/23/apple-openai-vie-for-ai-gadgets',
    # 'https://www.openpr.com/news/4360270/video-conferencing-software-market-valuation-expected-to-hit',
    # 'https://www.openpr.com/news/4360184/syringes-needles-market-report-cagr-6-4-key-players',
    # 'https://www.openpr.com/news/4360916/ai-in-energy-market-is-expected-to-reach-us-99-48-billion-by-2032',
    # 'https://www.openpr.com/news/4361153/smart-hospitals-market-set-to-reach-us-230-94-billion-by-2033',
    # 'https://www.openpr.com/news/4361111/e-merchandising-software-market-is-going-to-boom-adobe',
    # 'https://www.openpr.com/news/4360184/syringes-needles-market-report-cagr-6-4-key-players',
    # 'https://www.openpr.com/news/4360890/chromatography-market-to-reach-us-17-51-billion-by-2033-at-5-7',
    # 'https://www.tmonews.com/2026/01/t-mobile-vs-verizon-the-ongoing-dispute-over-honest-pricing-comparisons/',
    # 'https://tech.yahoo.com/phones/articles/not-t-not-verizon-jd-131500475.html?_guc_consent_skip=1769093415',
    # 'https://www.openpr.com/news/4361028/future-of-chipless-rfid-market-technological-advancements',
    # 'https://www.marketbeat.com/originals/is-abbotts-january-pullback-a-good-time-to-buy/',
    # 'https://www.openpr.com/news/4363683/dried-apple-market-2025-2033-global-industry-growth-analysis',
    # 'https://www.openpr.com/news/4362765/future-of-enterprise-asset-management-eam-tool-market',
    # 'https://www.openpr.com/news/4362749/key-trends-in-the-dissolved-gas-analysis-dga-for-power',
    # 'https://www.openpr.com/news/4362578/medical-device-cdmo-market-dynamics-and-contributions',
    # 'https://www.openpr.com/news/4362762/key-trends-in-the-information-lifecycle-management-market-with',
    # 'https://www.openpr.com/news/4362725/virtual-power-plant-vpp-system-software-market-innovations',
    # 'https://www.globenewswire.com/news-release/2026/01/23/3224882/28124/en/Whole-Genome-and-Exome-Sequencing-Global-Market-Review-2021-2025-and-Growth-Outlook-2026-2031-Featuring-Illumina-Thermo-Fisher-Scientific-BGI-Genomics-and-Other-Leading-Players.html',
    # 'https://www.openpr.com/news/4362762/key-trends-in-the-information-lifecycle-management-market-with',
    # 'https://www.globenewswire.com/news-release/2026/01/26/3225530/28124/en/Germany-POS-Terminals-Market-Outlook-2026-2031-Featuring-Profiles-of-Worldline-includes-Ingenico-Verifone-Systems-PAX-Technology-NCR-Voyix-Diebold-Nixdorf-and-More.html',
    # 'https://www.globenewswire.com/news-release/2026/01/26/3225546/28124/en/Hardware-Firewall-Market-Outlook-2026-2031-Featuring-Profiles-of-Fortinet-Palo-Alto-Networks-Cisco-Systems-Check-Point-Software-Technologies-Juniper-Networks-and-More.html',
    # 'https://www.webpronews.com/salesforces-agentforce-gamble-ai-promise-clashes-with-valuation-doubts/',
    # 'https://www.dailypolitical.com/2026/01/24/temenos-group-otcmktstmsny-versus-f5-nasdaqffiv-head-to-head-analysis.html',
    # 'https://www.globenewswire.com/news-release/2026/01/26/3225520/28124/en/Comparator-Drug-Sourcing-Global-Market-Review-2021-2025-and-Forecast-2026-2031-Featuring-Clinigen-BAP-Pharma-Group-Thermo-Fisher-Scientific-Laboratory-Corporation-of-America-Catale.html',
    # 'https://www.openpr.com/news/4362786/thin-film-piezo-mems-inkjet-printhead-market-dynamics',
    # 'https://uk.pcmag.com/wireless-carriers/162797/verizon-has-slight-edge-over-att-t-mobile-except-in-one-key-category',
    # 'https://www.dailypolitical.com/2026/01/25/reviewing-wipro-nysewit-mawson-infrastructure-group-nasdaqmigi.html',
    # 'https://www.globenewswire.com/news-release/2026/01/23/3224879/28124/en/Global-Asset-Tracking-Software-Market-Analysis-and-Growth-Outlook-to-2031-Featuring-Strategic-Profiles-of-Zebra-Technologies-IBM-Corporation-Honeywell-Datalogic-Trimble-and-Other-K.html',
    # 'https://www.openpr.com/news/4365976/news-application-market-2026-2033-growth-overview-facts',
    # 'https://whatech.com/og/markets-research/industrial/1009208-metaverse-retail-sector-overview-market-projections-and-growth-strategies-through-2035.html',
    # 'https://www.openpr.com/news/4365351/data-center-optical-transceiver-market-dynamics',
    # 'https://www.openpr.com/news/4365976/news-application-market-2026-2033-growth-overview-facts',
    # 'https://www.openpr.com/news/4365963/devops-market-is-going-to-massive-growth-by-2033-microsoft',
    # 'https://www.openpr.com/news/4365670/future-of-magnetocardiograph-system-market-analysis-led',
    # 'https://www.globenewswire.com/news-release/2026/01/27/3226724/28124/en/Global-Trends-Transforming-the-4K-Camera-Landscape-Emerging-Competitors-Blackmagic-Design-JVC-Hitachi-Z-CAM.html',
    # 'https://www.openpr.com/news/4365153/ndfeb-market-size-share-industry-analysis-and-forecast',
    # 'https://www.openpr.com/news/4365963/devops-market-is-going-to-massive-growth-by-2033-microsoft',
    # 'https://www.openpr.com/news/4365695/future-of-distributed-data-grid-software-market-analysis-led',
    # 'https://www.openpr.com/news/4365976/news-application-market-2026-2033-growth-overview-facts',
    # 'https://www.openpr.com/news/4365963/devops-market-is-going-to-massive-growth-by-2033-microsoft',
    # 'https://www.openpr.com/news/4365904/business-scheduling-software-market-set-to-witness-9-8-cagr',
    # 'https://www.openpr.com/news/4365695/future-of-distributed-data-grid-software-market-analysis-led',
    # 'https://www.openpr.com/news/4365797/leading-companies-fueling-growth-and-innovation-in',
    # 'https://www.openpr.com/news/4365904/business-scheduling-software-market-set-to-witness-9-8-cagr',
    # 'https://www.openpr.com/news/4365164/children-gps-trackers-market-expected-to-achieve-16-5-cagr',
    # 'https://www.openpr.com/news/4365695/future-of-distributed-data-grid-software-market-analysis-led',
    # 'https://www.straitstimes.com/singapore/singapore-among-slowest-growing-food-delivery-markets-in-asean-despite-regional-surge',
    # 'https://www.pressherald.com/2026/01/20/driver-suffered-medical-event-before-crashing-into-westbrook-att-store-police-say/',
    # 'https://www.fibre2fashion.com/news/textile-news/indian-economy-to-grow-7-5-7-8-in-fy2025-26-deloitte-307838-newsdetails.htm',
    # 'https://www.marketscreener.com/news/credit-data-company-experian-posts-quarterly-revenue-growth-reaffirms-annual-forecast-ce7e58dddf88f521',
    # 'https://www.moneycontrol.com/news/business/information-technology/ltimindtree-to-close-fy26-with-8-000-freshers-onboard-ceo-venu-lambu-says-future-of-it-hiring-is-skill-based-13782491.html',
    # 'https://economictimes.indiatimes.com/tech/information-tech/ai-native-deals-services-strengthening-it-spends-ltimindtree-ceo-venu-lambu/articleshow/126846679.cms',
    # 'https://www.benzinga.com/markets/equities/26/01/50027034/michael-burry-warns-government-intervention-wont-stop-ai-bubble-burst-the-problem-is-too-big-to-save',
    # 'https://www.livemint.com/companies/india-tech-mahindra-500m-telef-nica-o2-deal-europe-it-infrastructure-11768951331947.html',
    # 'https://www.benzinga.com/insights/short-sellers/26/01/50016811/peering-into-thermo-fisher-scientific-incs-recent-short-interest',
    # 'https://www.marketscreener.com/news/experian-reaffirms-fy-guidance-after-steady-q3-ce7e58d2d888f42d',
    # 'https://www.africaintelligence.com/north-africa/2026/01/22/oracle-seeks-to-revive-its-project-for-an-rd-centre-in-the-kingdom,110607838-art',
    # 'https://www.eagletribune.com/region/rosen-a-highly-recognized-law-firm-encourages-oracle-corporation-investors-to-secure-counsel/article_0b529939-84e3-5ada-bdd5-d29978d4c43d.html',
    # 'https://www.bdtonline.com/news/nation_world/rosen-a-highly-recognized-law-firm-encourages-oracle-corporation-investors-to-secure-counsel/article_b9966f29-de37-5cf6-89a4-391da68a1eb0.html',
    # 'https://www.business-standard.com/markets/news/lack-of-valuation-comfort-in-persistent-systems-126012101364_1.html',
    # 'https://www.benzinga.com/m-a/26/01/50032758/qiagen-explores-possible-sale-after-new-buyer-talks-report',
    # 'https://www.mlex.com/mlex/articles/2432873/salesforce-denied-australian-notification-waiver-for-agentic-marketing-supplier-deal',
    # 'https://www.benzinga.com/insights/analyst-ratings/26/01/50081150/demystifying-cognizant-tech-solns-insights-from-8-analyst-reviews',
    # 'https://www.berkshireeagle.com/online_features/press_releases/north-americas-largest-rv-dealers-still-failing-google-core-web-vitals--overfuel-reports-nearly/article_9153dde3-af72-54ab-9891-b42f4697f919.html',
    # 'https://www.reformer.com/online_features/press_releases/north-americas-largest-rv-dealers-still-failing-google-core-web-vitals--overfuel-reports-nearly/article_9d9551df-abe8-5226-adde-61fdcad945f9.html',
    # 'https://www.benzinga.com/insights/news/26/01/50067448/heres-how-much-you-would-have-made-owning-illumina-stock-in-the-last-20-years',
    # 'https://www.benzinga.com/trading-ideas/movers/26/01/50082570/salesforce-stock-boost-whats-really-happening',
    # 'https://www.benzinga.com/insights/news/26/01/50074788/heres-how-much-1000-invested-in-state-street-energy-select-sector-spdr-etf-5-years-ago-would-be-wor',
    # 'https://www.law360.com/articles/2434164/ill-judge-trims-false-ad-suit-over-abbott-formula',
    # 'https://www.benzinga.com/markets/large-cap/26/01/50105927/abbotts-india-unit-under-scrutiny-due-to-phensedyl-cough-syrup-supply-chain',
    # 'https://www.benzinga.com/news/26/01/50102551/tesla-to-360-here-are-10-top-analyst-forecasts-for-friday',
    # 'https://www.benzinga.com/markets/equities/26/01/50101684/abbott-laboratories-analyst-cuts-price-target-after-q4-miss-expects-sales-growth-to-accelerate-in-h2',
    # 'https://www.benzinga.com/insights/news/26/01/50143492/heres-how-much-1000-invested-in-adobe-20-years-ago-would-be-worth-today',
    # 'https://www.benzinga.com/insights/options/26/01/50135534/10-information-technology-stocks-whale-activity-in-todays-session',
    # 'https://www.law360.com/articles/2434166/court-urged-to-resist-apple-s-transfer-bid-in-ip-rico-suit',
    # 'https://www.law360.com/articles/2434322/masimo-chafes-against-apple-s-bid-to-duck-634m-ip-verdict',
    # 'https://www.bloomberg.com/news/articles/2026-01-23/doordash-uber-fail-to-block-nyc-tipping-law-from-taking-effect',
    # 'https://www.law360.com/articles/2434266/meta-youtube-sued-by-subject-of-viral-turo-dash-cam-clip',
    # 'https://news.bloomberglaw.com/esg/fedex-deaf-ex-employee-end-disability-bias-retaliation-suit',
    # 'https://www.newcastleherald.com.au/story/9161942/chatgpt-health-revolution-or-risk-for-australian-healthcare/',
    # 'https://www.benzinga.com/markets/tech/26/01/50146354/larry-ellisons-sailboat-split-with-wife-was-pivotal-here-is-what-the-oracle-founder-says-you-should-think-about-when-people-call-you-crazy',
    # 'https://www.benzinga.com/insights/news/26/01/50095716/a-look-into-pegasystems-incs-price-over-earnings',
    # 'https://www.benzinga.com/markets/equities/26/01/50125016/crm-stock-is-flashing-a-warning-signal-salesforces-operational-quality-remains-high-but-price-trends-turn-triple-red',
    # 'https://www.benzinga.com/Opinion/26/01/50133023/sp500-how-much-upside-is-left-what-a-4th-year-of-gains-could-look-like',
    # 'https://www.benzinga.com/insights/sector-etfs/26/01/50124235/leading-and-lagging-sectors-for-january-26-2026',
    # 'https://www.benzinga.com/insights/sector-etfs/26/01/50094387/leading-and-lagging-sectors-for-january-23-2026',
    # 'https://seekingalpha.com/article/4863132-capgemini-not-expensive-but-not-impressed-by-wns-acquisition',
    # 'https://www.benzinga.com/trading-ideas/movers/26/01/50171574/salesforce-stock-loses-ground-after-5-6-billion-army-contract',
    # 'https://www.benzinga.com/etfs/broad-u-s-equity-etfs/26/01/50174662/spy-record-highs-core-holding-or-crowded-trade',
    # 'https://www.benzinga.com/insights/sector-etfs/26/01/50153361/leading-and-lagging-sectors-for-january-27-2026',
    # 'https://www.benzinga.com/markets/tech/26/01/50153059/bill-ackman-alarmed-by-anthropic-ceos-warning-that-ai-models-developed-evil-persona-during-training-very-concerning',
    # 'https://news.bloomberglaw.com/banking-law/ubs-asks-us-court-to-throw-hayes-400-million-libor-suit-out'
]

# -----------------------------
# Event Keywords for Location-based News
# -----------------------------
EVENT_KEYWORDS = [
    # Natural disaster – underway
    "flood",
    "earthquake",
    "wildfire",
    "tsunami",
    "cyclone",
    "hurricane",
    "landslide",
    "volcanic",
    "evacuation",

    # Natural disaster – potential
    "flood_warning",
    "earthquake_warning",
    "tsunami_warning",
    "storm_warning",
    "disaster_alert",

    # Significant weather – underway
    "heavy_rain",
    "storm",
    "heatwave",
    "coldwave",
    "extreme_weather",

    # Significant weather – potential
    "weather_alert",
    "rainfall_forecast",
    "heatwave_warning",

    # Terror event
    "terror",
    "bombing",
    "armed_attack",
    "explosion",

    # Civil unrest
    "mass_protest",
    "protest",
    "riot",
    "curfew",
    "unrest",

    # Health / disease
    "outbreak",
    "epidemic",
    "pandemic",
    "public_health",

    # Environment
    "air_pollution",
    "smog",
    "aqi",
    "water_contamination",

    # Infrastructure disruption
    "power_outage",
    "blackout",
    "telecom_outage",
    "internet_shutdown",
    "water_disruption",

    # Cyber
    "cyberattack",
    "ransomware",
    "data_breach",

    # Transport / aviation
    "airport_shutdown",
    "flight_cancelled",
    "airspace_closed",

    # Traffic
    "traffic_congestion",
    "road_blockage",

    # Supply chain / port
    "port_congestion",
    "supply_chain",

    # Financial / geopolitical
    "bankruptcy",
    "insolvency",
    "sanctions",
    "embargo"
]
